### ISSUE TITLE
[I/O Site] investigate decoupling the theme from the new I/O site after launch

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#10]
Once we migrate I/O to a stand alone Gatsby Site, We have an opportunity to decouple this site from our[ Gatsby Theme ](https://github.com/newrelic/gatsby-theme-newrelic)as we've begun to take a different approach to this site where keeping it dependent on the theme may no longer make sense.

### Acceptance Criteria

- [ ] Audit I/O site and determine what would need to be rebuilt in the I/O site if we de-coupled the theme 
- [ ] Consider the impacts and effort to decouple the theme
- [ ] Plan out the work and break down the work

**Comment by jpvajda** [comment]
With the hand off the I/O site to CXP-UI, I'm curious if we still want to consider this, or if it makes sense to keep the I/O site dependent on the theme for consistency purposes, @roadlittledawn / @zstix  any thoughts?

**Comment by jpvajda** [comment]
we discussed and at this time we felt it wasn't necessary , but this can be evaluated in the future by CXP-UI

**Comment by hveerendranath** [comment]
@jpvajda -created JIRA ticket CXPUI-47. I am sure team will have questions on this ticket, will try to reach out to you/your team.
