### ISSUE TITLE
[I/O Site] handle cache settings at site level

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#22]
currently have site cache settings defined on fastly to 1hr, we'll want to control that at the site level, so it's not at the CDN Level. 

### Acceptance Criteria
- [ ] update the [site wiki ](https://github.com/newrelic/instant-observability-website/wiki)with documentation the use of Fastly, caching and other useful info

**Comment by jpvajda** [comment]
@aswanson-nr is this something we are still concerned with? If so it may be a good idea to sort this out before handing off to CXP-UI

**Comment by aswanson-nr** [comment]
@jpvajda The fastly cache settings have worked fine for us so far. I'm okay with leaving them in.
