### ISSUE TITLE
[I/O Site] Update event documentation for new site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#23]
Now that the site is officially moved, we need to ensure we document all our event information for Tessen, GA, etc. 

### Acceptance Criteria

- [x] the I/O site repo wiki is updated with all the applicable event information found on the [developer site wiki](https://github.com/newrelic/developer-website/wiki/Event-Data-and-Instrumentation)

**Comment by jpvajda** [comment]
@aswanson-nr was going to review this wiki for accuracy before we mark it done

**Comment by aswanson-nr** [comment]
Audited the wiki and removed some unused events. Also noticed that one wasn't being generated as documented, PR to update that event [here](https://github.com/newrelic/instant-observability-website/pull/33)
