### ISSUE TITLE
Terraform logo is overlapping text on the I/O site `Firefox only`🦊

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#24]
### Steps to reproduce

> this is only an issue on Firefox. 

go to the [terraform quickstart page](https://developer.newrelic.com/instant-observability/terraform/ba9ce393-d85f-4e40-81a7-d52b2c6ad213/) on the external I/O site
look at the logo. 👀 

### screen shots

<img width="1871" alt="Screen Shot 2022-02-10 at 2 57 45 PM" src="https://user-images.githubusercontent.com/1395158/153503648-98d7e9df-cd31-4101-bd12-96e7b9a30b84.png">

<img width="1385" alt="Screen Shot 2022-02-10 at 2 57 16 PM" src="https://user-images.githubusercontent.com/1395158/153503664-32bd7e86-b96a-4211-9aba-a5a7060fa50f.png">

### expected 

- logo doesn't overlap text on page 
- fix this issue in the[ terraform quickstart ](https://github.com/newrelic/newrelic-quickstarts/tree/main/quickstarts/observability-as-code/terraform)

**Comment by jpvajda** [comment]
I've asked CXP-UI if they can resolve this one for the site.

**Comment by hveerendranath** [comment]
@jpvajda JIRA ticket CXPUI-43 created in order to address this issue by CXPUI team, you may close the PR.
