### ISSUE TITLE
[I/O site] Code Review & Merge `CXP-UI` PRs

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#34]
### Acceptance Criteria

- [ ] Review all linked PRs and code review them
- [ ] Merge in when complete 
- [ ] cut a release of the site after the PRs are merged

**Comment by aswanson-nr** [comment]
Started the review process. Currently waiting for the build service to be available to forked PRs, then we can start merging.

**Comment by josephgregoryii** [comment]
Looks like this got moved to `Done` before closing out all tickets. Are the other 2 tickets still waiting for approval/merging?

cc: @jpvajda @aswanson-nr @RavitejaSurampudi

**Comment by aswanson-nr** [comment]
This is almost done, just waiting on some conflict resolutions for #29
