### ISSUE TITLE
[I/O site] Review our approach to APDEX alerting for the site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#40]
[APDEX ](https://www.freshworks.com/website-monitoring/what-is-apdex/)alerts are being triggered for the I/O site now that we move to the newrelic.com domain and we want to better understand the use of the alert and what we should focus on to try to resolve this alert. 

### Acceptance Criteria 

- [ ] Discuss our use of APDEX and if it's useful and what it means to our team 
- [ ] Consider if this alert should be modified or turned off
  - If this is a metric we want to keep, perhaps we turn off PagerDuty alerting but still keep some light alerting. So if this triggers, we know, but dont have to wake up in the middle of night to not be able to resolve it.
- [ ] Better understand our network topology for our use of Gatsby Cloud, it's on Fastly under the hood. 
- [ ] Take next steps, file tickets, etc.

**Comment by jpvajda** [comment]
@aswanson-nr / @zstix 👋  feel free to add to this ticket.

**Comment by aswanson-nr** [comment]
@jpvajda This looks great! I'm going to write another ticket for the image handled, since we will want to get that done either way.

**Comment by hveerendranath** [comment]
@jpvajda created JIRA ticket CXPUI-48. will get back to the team if required more info/any help
