### ISSUE TITLE
[SSR Public Catalog] Create a 500 error page

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/instant-observability-website#46]
## Description
With the transition to using SSR for the I/O catalog pages, we now have the possibility to hit a 500 HTTP error on these pages.

### Design Questions

- [x] What is the preferred design for a [500 error](https://www.ionos.com/digitalguide/hosting/technical-matters/http-error-500-internal-server-error/) given we can load most of our components (see below) but not the navigation or search given that will be powered by the catalog service & SSR.
- [x] This is only for the I/O experience and doesn't really apply to the dev , docs or oss sites as those sites don't use the catalog service or SSR So we don't have to apply this solution to those sites.
- [x] Review language with UI-Writing team for suggestions.

### Design References 🎨 

*What components will load and fail to load in case of a 500*

<img width="1719" alt="Screen Shot 2021-12-07 at 4 13 14 PM" src="https://user-images.githubusercontent.com/1395158/145124375-6b121de9-b1c5-42ce-94ff-3c805035de31.png">

<img width="1437" alt="Screen Shot 2021-12-07 at 4 13 25 PM" src="https://user-images.githubusercontent.com/1395158/145121124-c2c7d9d2-4f40-43bc-aba7-6d1db3d8afd2.png">

### Mock Up 🧑‍🎨 

<img width="1677" alt="(I:O 500 error " src="https://user-images.githubusercontent.com/1395158/145863395-b6984f62-2a33-484d-a45c-ca4440818c34.png">

### Links
- [Gatsby 500 page docs](https://www.gatsbyjs.com/docs/how-to/adding-common-features/add-500-page/)

### Error message content

> We are currently experiencing technical issues loading the Instant Observability catalog. Please use the guided install tile below to start the install process. 

### Acceptance Criteria 

- [x] a design is provided that we can use
- [x] Ensure this approach works on mobile 
- [x] a 500 page is visible when running `yarn develop` at `localhost:8000/500`
- [ ] a 500 page is visible when the catalog service fails to load the navigation of I/O.

**Comment by aswanson-nr** [comment]
@jpvajda and @legnaleama, are these mocks still good post redesign?

**Comment by jpvajda** [comment]
👋  the last we spoke (if I recall)  it's totally fine to go with this for our initial approach as this page isn't expected to be visible often. we can always revisit the design in a second iteration as needed.

**Comment by tabathadelane** [comment]
@jpvajda Our current site does not have the IO logo/blurb in the sidebar anymore. It's easy to re-add this just for the 500 page, or we could remove the sidebar on this page all altogether. Is there a preference? Here is my current local branch with both options. Let me know, and I can submit a PR!
<img width="1303" alt="Screen Shot 2022-03-02 at 11 32 58 AM" src="https://user-images.githubusercontent.com/47728020/156435994-e72abed2-167b-4e96-8516-ab6bc0829503.png">
<img width="1303" alt="Screen Shot 2022-03-02 at 11 33 37 AM" src="https://user-images.githubusercontent.com/47728020/156436007-47d3527c-f587-42de-ab6a-facf54aebeea.png">

**Comment by jpvajda** [comment]
@tabathadelane thanks for pointing that out. I think we should add it back, as without , it lacks context for the user. If we can also include the line divider, which is used to seperate the nav from the page content that would also be nice for separation.
