### ISSUE TITLE
[SSR Public Catalog] Document Gatsby SSR and update Runbooks

### ISSUE THREAD

**Issue by zstix** [newrelic/instant-observability-website#47]
## Description
While switching [from manually fetching JSON to Gatsby SSR functions](newrelic/instant-observability-website#43), we added [some additional instrumentation and alerting](newrelic/instant-observability-website#45). To help make on-call shifts easier, we should add information about this to our [Emergency Runbook](https://github.com/newrelic/developer-website/wiki/Emergency-Runbook).

## Acceptance Criteria
* [x] newrelic/instant-observability-website#45
* [x] Update README to explain how the Gatsby SSR + NerdGraph code works (with lots of documentation links, plz)
* [x] Update [Emergency Runbook](https://github.com/newrelic/instant-observability-website/wiki/Emergency-Runbook) to include information about new alerts
* [x] Add a diagram about how the SSR pages work on the I/O site
* [x] Update our [troubleshooting dashboard](https://staging.onenr.io/0JBQr66VbQZ) to reflect the new alerts / instrumentation

**Comment by aswanson-nr** [comment]
Merged into feature branch
