### ISSUE TITLE
[SSR Public Catalog] Disable PR previews for forks

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/instant-observability-website#48]
## Summary
With the SSR changes, we now have new environment variables that we do not want stolen. Unfortunately, the `Gatsby Build Service` does not support waiting to run until the workflows are approved and will just immediately run for forks (when turned on, which it currently is 02/24/2022). So running on forks will need to be disable until such time that the service supports a safe forked workflow.

## AC
- [x] Ask Gatsby support to disable previews for forked pull requests
- [x] Test that the `Gatsby Build Service` does not run for a forked PR

**Comment by nr-kkenney** [comment]
PR previews for forks have been disabled. Example: https://github.com/newrelic/instant-observability-website/pull/56.
