### ISSUE TITLE
[I/O site] Site doesn't have a 3rd party notice file

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#52]
Similar to the developer site we should auto generate a 3rd party notice file to comply with our OSS policies 

https://github.com/newrelic/developer-website/blob/develop/THIRD_PARTY_NOTICES.md

### Questions

- Do we actually need this? the Docs site doesn't have one.
> yes, @melissaklein24 confirmed if any repo uses a dependency, this is required. 
- This file seems to be auto generated by the OSS bot. 🤷  How does this work exactly?
> it's run with a workflow job
- We mention this file in our readme, but we don't actually have a file for third party notices.
> let's add one

### Acceptance Criteria

- [x] Determine if this file is even required anymore in OSS
- [x] Generate a third party notice file called `THIRD_PARTY_NOTICES.md` in the root directory
- [x] Consider if the docs site repo needs one @roadlittledawn

**Comment by zstix** [comment]
It looks like this is generated in a release workflow: https://github.com/newrelic/developer-website/actions/runs/1884448849/workflow#L13-L120
