### ISSUE TITLE
[I/O Site] Account transfers and access for CXP-UI

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#68]
The following accounts changes will need to be made to support the handoff of the I/O site to CXP-UI

### DevEn Team considerations

- [x] Ensure the team has Gatsby cloud access  (to the I/O site specifically, not all sites)
- [x] Share the DevEn dashboards New Relic so they can copy what they need to their new team account.
- [x] Ensure the team is setup in Github org
- [x] Ensure team has admin on GH repo for the i/o site
- [ ] Ensure DevEn is no longer the admin of the repo. 
- [ ] ~~Generate new  API key for their staging account~~ N/A
- [ ] ~~Add that API key to Gatsby Cloud and Github~~ N/A
- [x] Let the analytics team know CXP-UI is taking over the site.

### CXP-UI Team considerations

- [x] Ensure the team has GA access so they can see analytics data.
- [x] Ensure the PM / Eng Manager has Segment access to the i/o source. 
- [x] Make a new team on Staging for CXP-UI if doesn't already exist. 
- [x] Confirm if this team has prod access in OKTA for pager duty and AWS
- [x] Ensure team is setup in pager duty, they'll need to create a pager duty team

**Comment by jpvajda** [comment]
@aswanson-nr could you add a comment on what this is blocked by?

**Comment by aswanson-nr** [comment]
Blocked while we wait for CXP-UI to get setup.

**Comment by jpvajda** [comment]
@aswanson-nr do we need them to take any actions to unblock this? if so we can communicate that to their team, just let me know.

**Comment by aswanson-nr** [comment]
Back to blocked as we wait for access to the CXP-UI staging account.

**Comment by aswanson-nr** [comment]
Letting the data flow for a bit before removing us as admins

**Comment by aswanson-nr** [comment]
Leaving admin access for now, seems like it could be needed in the future.
