### ISSUE TITLE
[I/O Site] Carousel bunches up quickstarts on page load with small screen sizes

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/instant-observability-website#79]
## Description

When a user navigates to the site, if they are viewing the site on mobile or a smaller screen size, the carousel bunches up the quickstarts before the CSS kicks in and fixes it.

<details>
<summary>Reference to issue</summary>

![Screen Shot 2022-03-11 at 11 52 07](https://user-images.githubusercontent.com/56952981/157975060-3248210e-67ab-4679-8960-2d8ab1b3f7ce.png)

</details>

## Acceptance Criteria

- [ ] Create a transition to display the carousel (TBD)
- [ ] Ensure the carousel has the CSS properties loaded before displaying
- [ ] Ensure the changes work at different width breakpoints and mobile view

**Comment by jpvajda** [comment]
I'm going to bring this to attention of the CXP-UI team to see if they can resolve it, as it was introduced in their carousel feature.

**Comment by jpvajda** [comment]
closing.
