### ISSUE TITLE
[I/O] Code stream quickstart CSS issue with logo

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#86]
This quickstart seems to have different CSS on it, which shrinks the image rather than removing the picture at a certain breakpoint

### Steps to reproduce 

1. Go to: https://newrelic.com/instant-observability/codestream/29bd9a4a-1c19-4219-9694-0942f6411ce7
2. resize your view 
3. see the logo shrink very small

### Image

<img width="1041" alt="Screen Shot 2022-03-11 at 5 28 54 PM" src="https://user-images.githubusercontent.com/1395158/157995430-90fdf61e-624c-4864-928a-08fd2f70847f.png">

### Expected

The logo doesn't shrink so small and is better represented at small screen sizes.

### Quickstart note 

The logo file is an [SVG,](https://github.com/newrelic/newrelic-quickstarts/blob/63ed203f78ec7eec1ff1cff7419d8d4abef2ccf1/quickstarts/codestream/codestream/logo.svg) so I'm wonder if it's a fix to the logo itself.

**Comment by dikshab0202** [comment]
https://user-images.githubusercontent.com/101187392/158587786-f848c0cf-28eb-4fa7-a901-69158d59b355.mov

https://user-images.githubusercontent.com/101187392/158587839-bfc24d32-fd8c-4d3d-993e-fd65d0b3d58f.mov

@jpvajda could you please check the above attached videos which is before and after fix and is it the expectation regarding the logo issue?

**Comment by jpvajda** [comment]
@dikshab0202 This looks great. can you link your PR to this issue?

**Comment by hveerendranath** [comment]
@jpvajda CXPUI-39 created to take care of this, you may close the PR.

**Comment by jpvajda** [comment]
@hveerendranath Thanks! Just a note : these are `Issues` in github not `PRs`.

**Comment by jpvajda** [comment]
I added 1pt for code review efforts
