### ISSUE TITLE
[I/O Site] Rapidly clicking on the next button for the dashboard carousel causes overlap

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/instant-observability-website#90]
TBD

**Comment by jpvajda** [comment]
@josephgregoryii could you provide some more details on this bug?

**Comment by josephgregoryii** [comment]
@jpvajda I did some testing on the production site and didn't find any weird overlap - it might have just been an SSR issue. I will close this issue as I cannot reproduce the bug on main
