### ISSUE TITLE
[I/O Site] Mobile: when initially loading the landing page, the carousel layout is not mobile optimized

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#91]
We should better optimize the responsiveness of the carousel on load.

`JIRA` `CXPUI-38`

### Steps to reproduce 

1. load the I/O home page on a mobile view
2. see it takes the carousel 1 - 2 secs to snap to the responsive size.

### Screen shot 

<img width="410" alt="Screen Shot 2022-03-11 at 5 46 16 PM" src="https://user-images.githubusercontent.com/1395158/157996297-cb6d6e3f-b80b-4da2-a296-995f7ba1b8ac.png">

**Comment by hveerendranath** [comment]
@jpvajda JIRA ticket CXPUI-38 is created and team will check on this. When i tried to reproduce screen loaded fine, will try to reach out if incase requires any help. for time being this PR can be closed.
