### ISSUE TITLE
No error message populated on NerdGraphRequest event when we purposefully broke API key environment variable [dev]

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#94]
## Summary
Error events are being sent, but the errorMessage attribute / field is empty. Looking at the code, its because we are sending the entire `error` object, rather than `error.message`. So this is a fairly simple fix that needs to happen in two places: the catalog page, and the quickstart details page.

## Acceptance Criteria
- [x] Events have populated error messages

**Comment by jpvajda** [comment]
@nr-kkenney can you link your PR to this ?

**Comment by jpvajda** [comment]
I assume we can close this out with out merging the PR given our decision is not to release SSR, can you confirm if that is true @nr-kkenney ?

**Comment by nr-kkenney** [comment]
@jpvajda yep. we can close this out.
