### ISSUE TITLE
[I/O Site] Update fetch quickstart workflow to pull from catalog service

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#95]
### ISSUE

We disabled [Fetch Quickstarts](https://github.com/newrelic/instant-observability-website/actions/workflows/fetch-quickstarts.yml) to allow us to launch the [Carousel feature](https://github.com/newrelic/instant-observability-website/pull/50)  but there is hero requst to update the external site with cloud flare content (See [PR](https://github.com/newrelic/newrelic-quickstarts/pull/915/files))  as there is launch today with a partner. 

`as a note:` this workflow has been off for 13 days, and the SRR work would make this workflow irrelevant but we still have bugs to resolve before we can release SSR.

### Steps to reproduce 

look for cloudflare on the external site, then look for cloudflare in the internal catalog, notice it's only visible internally.

### Expected

We can see cloud flare on the external site. 

**can we either** 
1.  re-enable the workflow, so we can update the quickstart content. then disable it again.
2. Manually update the site to include cloudflare quickstart.

**Comment by zstix** [comment]
After discussing this, we've decided to update the workflow to pull from the catalog service, rather than manually updating the quickstart JSON (which feels kinda hacky).
